Blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from .api_urls import urlpatterns as api_urls
#from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('modules.Home.urls',namespace='Home',app_name='Home')),
    url(r'^publicaciones/', include('modules.Publicaciones.urls',
    namespace='Publicaciones',app_name='Publicaciones')),

    #url de API

    url(r'^api/v1/', include(api_urls)),

]

modules/Home/urls.py
from django.conf.urls import url
from .views import Index,Contacto,Otros,Signup,Login,Logout

urlpatterns = [
    url(r'^$', Index, name='index'),
    url(r'^contacto/$', Contacto, name='contacto'),
    url(r'^otros/(?P<num>[0-9]+)/(?P<num2>[0-9]+)/$', Otros, name='otros'),
    url(r'^signup/$', Signup, name='Signup'),
    url(r'^login/$', Login, name='Login'),
    url(r'^logout/$',Logout, name='Logout')
    #url(r'^$', admin.site.urls),
]

modules/Publicaciones/urls.py
from django.conf.urls import url
from .views import Index,Add

urlpatterns = [
    url(r'^$', Index, name='index-publicacion'),
    url(r'^add/$', Add, name='add-publicacion'),

]

modules/Publicaciones/models.py
from django.db import models
from modules.Usuarios.models import User

TAGS = (
        ('TC','Tecnología'),
        ('CT','Científico'),
        ('PR','Programación')
)
"""
class PepePublicacionesManager(models.Manager):

    def get_queryset(self):
        return super(PepePublicacionesManager,self).get_queryset().filter(autor__username="Pepe")
"""
class Publicacion (models.Model):
    id  = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=80)
    contenido = models.TextField()
    fecha  = models.DateField(auto_now_add=True)
    autor = models.ForeignKey(User,on_delete=models.CASCADE, related_name="publicaciones")
    tags = models.CharField(choices=TAGS,max_length=50)
    imagen = models.ImageField(upload_to='Publicaciones/',null=True,blank=True)


    #pepe_publish = PepePublicacionesManager()

    def __str__(self):
        return "%s %s" % ("Publicacion: ",self.nombre)

modules/Usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin

class UserManager(BaseUserManager, models.Manager):

    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):

        if not email:
            raise ValueError('El email debe ser obligatorio')
        email = self.normalize_email(email)

        user = self.model(email=email,
                          is_active=True, is_staff=is_staff,
                          is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(
            email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(
            email, password, True, True, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin, models.Model):

    # unique, no se van a repetir
    id_usuario = models.AutoField(primary_key=True, unique=True)
    nombre = models.CharField(max_length=40)
    apaterno = models.CharField(max_length=25)
    amaterno = models.CharField(max_length=25)
    direccion = models.TextField()
    telefono = models.CharField(max_length=22)
    email = models.CharField(unique=True, max_length=50)
    genero = models.CharField(choices=(('M','Mujer'),('H','Hombre')), max_length=16,blank=True)


    # intermediario entre trans de cada modelo, object managaer de cada modelo
    objects = UserManager()

    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    def get_short_name(self):
        return self.nombre

modules/Home/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User


class LoginForm(ModelForm):

    class Meta:
        model = User
        fields = ['username','password']

modules/Home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from .forms import LoginForm
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def Index(request):
    user = request.user

    return render(request,'Home/index.html',{"user":user})


def Contacto(request):

    return HttpResponse('Pagina de contactos')

def Otros(request,num,num2):

    return HttpResponse('Pagina de otros numero: <b> '+num+'</b>')

def Signup(request):

    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            user = None
        if user is  None:
            user = User.objects.create_user(
            first_name=first_name,
            last_name=last_name,
            username=username,
            password=password)
            user.save()
            return HttpResponse('<b>Usuario Registrado<b>')
        else:
            return HttpResponse('<b>El usuario que ingresaste ya existe<b>')


    else:
        return render(request,'Home/signup.html')

def Login(request):

    if request.method == 'POST':

        user = authenticate(username=request.POST['username'],
        password=request.POST['password'])

        if user is not None:
            login(request,user)
            return redirect('Home:index')

        else:
            return HttpResponse("Error en usuario o contraseña")

    else:
        return render(request,'Home/login.html')


def Logout(request):
    logout(request)
    return redirect('Home:index')

modules/Publicaciones/views.py
from django.shortcuts import render,redirect
from .models import TAGS,Publicacion
from .functions import handle_uploaded_file
def Index(request):

	public = [
		{	"Nombre":"Mi primer Proyecto en Django",
			"Autor":"Edwin Salgado",
			"Fecha":"7-02-2017",
			"Rating":5
		},

		{	"Nombre":"API Rest",
			"Autor":"Paco Ocampo",
			"Fecha":"7-02-2017",
			"Rating":1

		},

		{	"Nombre":"Angular for noobs",
			"Autor":"Uriel Torres",
			"Fecha":"7-02-2017",
			"Rating":4
		},
	]

	return render(request,'Publicaciones/index.html',{ "publicaciones":public })



def Add(request):

	if request.method == 'POST':
		if request.user.is_authenticated():
			types = {'image/jpeg':'.jpg','image/png':'.png','image/gif':'.gif'}
			image_name = request.FILES['imagen'].name+types[request.FILES['imagen'].content_type]
			publicacion = Publicacion()

			publicacion.nombre = request.POST['nombre']
			publicacion.contenido = request.POST['contenido']
			publicacion.tags = request.POST['tag']
			publicacion.autor = request.user
			publicacion.imagen = handle_uploaded_file(request.FILES['imagen'],image_name)

			publicacion.save()

			return redirect('Publicaciones:index-publicacion')

	else:
		dict_tags = dict((x,y) for x,y in TAGS)
		return render(request,'Publicaciones/add.html',{"tags":dict_tags})

modules/Usuarios/views.py
from django.shortcuts import render

# Create your views here.

templates/Home/index.html
{% extends 'base.html'%}
{% load static %}
{% block 'title' %}Home{%endblock%}
{% block 'content'%}
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  Error alias doloribus dolores fuga enim sint ad nam magnam eius beatae.
  Nemo nulla necessitatibus cumque enim, dolorem vitae non aperiam voluptatum!</p>

{%endblock%}

templates/Home/login.html
{% extends 'base.html'%}
{% load static %}
{% block 'title' %}Login{%endblock%}
{% block 'content'%}
<form class="col 12" action="{% url 'Home:Login' %}" method="post">
{% csrf_token %}
<div class="row">
  <div class="input-field col s12">
    <input id="username" type="text" class="validate" name="username">
    <label for="username">Username</label>
  </div>
</div>
<div class="row">
  <div class="input-field col s12">
    <input id="password" type="password" class="validate" name="password">
    <label for="password">Password</label>
  </div>
</div>

<input type="submit" name="" value="Enviar">
</form>

{%endblock%}

templates/Home/signup.html
{% extends 'base.html'%}
{% load static %}
{% block 'title' %}Signup{%endblock%}
{% block 'content'%}
<div class="row">
<form class="col s12" action="{% url 'Home:Signup' %}" method="POST" >
 {% csrf_token %}
 <div class="row">
   <div class="input-field col s6">
     <input  id="first_name" type="text" class="validate" name="first_name">
     <label for="first_name">First Name</label>
   </div>
   <div class="input-field col s6">
     <input id="last_name" type="text" class="validate" name="last_name">
     <label for="last_name">Last Name</label>
   </div>
 </div>
 <div class="row">
   <div class="input-field col s12">
     <input id="username" type="text" class="validate" name="username">
     <label for="username">Username</label>
   </div>
 </div>
 <div class="row">
   <div class="input-field col s12">
     <input id="password" type="password" class="validate" name="password">
     <label for="password">Password</label>
   </div>
 </div>

 </div>
 <input type="submit" name="Enviar" value="Enviar" >
</form>
</div>
{%endblock%}

templates/Publicaciones/add.html
{% extends 'base.html'%}
{% block 'title' %}Publicaciones|add{%endblock%}
{% block 'content'%}
	<form class="" action="{% url 'Publicaciones:add-publicacion' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="row">
        <div class="input-field col s6">
          <input  id="Nombre" type="text" name="nombre" class="validate">
          <label for="first_name">Nombre</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <textarea   type="text" name="contenido" class="validate"></textarea>
          <label for="first_name">Contenido</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <select class="" name="tag">
            <option value="" selected>--Seleciona opcion---</option>
          {%for key,value in tags.items %}
            <option value="{{key}}">{{value}}</option>
          {%endfor%}
          </select>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input name="imagen" id="" type="file" class="validate" accept="image/x-png,image/gif,image/jpeg" >
          <label for="first_name">Imagen</label>
        </div>
      </div>
      <input type="submit" name="" value="Enviar">
	</form>


{%endblock%}

{%block 'scripts'%}
<script type="text/javascript">
  $('document').ready(function() {
    $('select').material_select();
  })
</script>

{%endblock%}

templates/Publicaciones/index.html
{% extends 'base.html'%}
{% load static %}
{% block 'title' %}Publicaciones{%endblock%}
{% block 'content'%}
	{%comment%}
	{{publicaciones.Nombre | lower}}
	{{publicaciones.Edad | default:"No tiene"}}
	{{publicaciones.Nombre | length}}
	{%endcomment%}
		{% for publicacion in publicaciones %}
			{% for key,value in publicacion.items %}
				{{key}}:{{value}}
			<br>
			{%endfor%}
			<br>
			<hr>
		{%endfor%}

<a href="{% url 'Publicaciones:add-publicacion' %}">Crear publicacion</a>

{%endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block 'title' %} {%endblock%}</title>
  <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
</head>
<body>
  <nav>
   <div class="nav-wrapper">
     <a href="#" class="brand-logo">Blog backend</a>
     {%if user.is_authenticated %}
     <span style="margin-left:50%;">Hola: {{user.username}}</span>
     <a href="#">Mi perfil</a>
     <a href="{% url 'Publicaciones:index-publicacion'%}">Mis publicaciones</a>
      <a href="{% url 'Home:Logout'%}">Logout</a>
      {%else%}
     <ul id="nav-mobile" class="right hide-on-med-and-down">
       <li><a href="{% url 'Home:Signup' %}">Sign up</a></li>
       <li><a href="{% url 'Home:Login' %}">Log in</a></li>
     </ul>
     {% endif %}
   </div>
 </nav>

  {%block 'content'%}
  {%endblock%}

  <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/materialize.min.js' %}"></script>
  {%block 'scripts'%}
  {%endblock%}
</body>
</html>